myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('products/',views.products,name='products'),
    path('products/<int:pk>/',views.ProductDetailView.as_view(),name='productdetail'),
    path('products/add/',views.ProductCreateView.as_view(),name='add_product'),
    path('products/update/<int:pk>/',views.ProductUpdateView.as_view(),name='update_product'),
    path('products/delete/<int:pk>/',views.ProductDeleteView.as_view(),name='delete_product'),
    path('products/mylistings',views.my_listings,name='mylistings'),
    path('success/',views.PaymentSuccessView.as_view(),name='success'),
    path('failed/',views.PaymentFailedView.as_view(),name='failed'),
    path('api/checkout-session/<id>',views.create_checkout_session,name='api_checkout_session')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
]

# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = 'users'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',views.profile,name='profile'),
    path('createprofile/',views.createprofile,name='createprofile'),
    path('sellerprofile/<int:id>/',views.seller_profile,name='sellerprofile'),
]
 

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg',upload_to='profile_pictures')
    contact_number = models.CharField(max_length=100,default="99999999")

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserFrom(UserCreationForm):
    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'class':'focus:outline-none','placeholder':'demo@gmail.com'}))
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'focus:outline-none','placeholder':'user123'}))
    password1 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    password2 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))

    class Meta:
        model = User
        fields = ("username","email","password1","password2")
    
    def save(self,commit=True):
        user = super(NewUserFrom,self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

users/views.py
from multiprocessing import context
from django.shortcuts import render,redirect
from .forms import NewUserFrom
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = NewUserFrom(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('myapp/products')

    form = NewUserFrom()
    context ={
        'form':form,
    }
    return render(request,'users/register.html',context)

@login_required
def profile(request):
    return render(request,'users/profile.html')

def createprofile(request):
    if request.method == 'POST':
        contact_number = request.POST.get('contact_number')
        image = request.FILES['upload']
        user = request.user
        profile = Profile(user=user,image=image,contact_number=contact_number)
        profile.save()
    return render(request,'users/createprofile.html')

def seller_profile(request, id):
    seller = User.objects.get(id=id)
    context = {
        'seller':seller,
    }
    return render(request,'users/sellerprofile.html',context)

users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="">Upload profile image</label>
        <input class="py-2" placeholder="upload profile image" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        <label for="">Contact number</label>
        <input class="shadow appearance-non border rounded py-2 px-3 mr-10 text-gray-700" placeholder="99999999" type="text" accept="image/*" name="contact_number" id="contact_number">
    </div>
    <input class="bg-green-500 text-while px-5 py-2" name="Add" type="submit">
</form>
{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">🧑‍💻 Login From</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Username</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
            {{ form.username }}
        </div> 
        </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Confirm Password</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
            {{ form.password }}
        </div> 
        </div>
        <button class="bg-green-500 text-white px-5 py-2" type="submit">Login</button>
    </form>
    <div class="m-10">Do not have an account? <a class="text-indigo-500" href="{% url 'users:register' %}">Register</a></div>
    
</div>

{% endblock %}

users/templates/users/logout.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1>You are logedout</h1>
{% endblock %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            <img src="{{user.profile.image.url}}">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">{{ user.username }}</div>
        <div class="font-bold text-xl mb-2 px-6 py-4">📞{{ user.profile.contact_number }}</div>
    </div>
</div>


{% endblock %}

users/templates/users/register.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">🧑‍💻 User Register From</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Username</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
            {{ form.username }}
        </div> 
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Email</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
            {{ form.email }}
        </div> 
        </div>
         
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Password</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
            {{ form.password1 }}
        </div> 
        </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Confirm Password</label>
        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
            {{ form.password2 }}
        </div> 
        </div>
        <button class="bg-green-500 text-white px-5 py-2" type="submit">Register</button>
    </form>
    <div class="m-10">Already have an account? <a class="text-indigo-500" href="{% url 'users:login' %}">Login</a></div>
</div>

{% endblock %}

users/templates/users/sellerprofile.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            <img src="{{seller.profile.image.url}}">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">{{ seller.username }}</div>
        <div class="font-bold text-xl mb-2 px-6 py-4">📞{{ seller.profile.contact_number }}</div>
    </div>
</div>


{% endblock %}