myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('products/',views.products,name='products'),
    path('products/<int:pk>/',views.ProductDetailView.as_view(),name='productdetail'),
    path('products/add/',views.ProductCreateView.as_view(),name='add_product'),
    path('products/update/<int:pk>/',views.ProductUpdateView.as_view(),name='update_product'),
    path('products/delete/<int:pk>/',views.ProductDeleteView.as_view(),name='delete_product'),
    path('products/mylistings',views.my_listings,name='mylistings'),
    path('success/',views.PaymentSuccessView.as_view(),name='success'),
    path('failed/',views.PaymentFailedView.as_view(),name='failed'),
    path('api/checkout-session/<id>',views.create_checkout_session,name='api_checkout_session')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
]

# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = 'users'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',views.profile,name='profile'),
    path('createprofile/',views.createprofile,name='createprofile'),
    path('sellerprofile/<int:id>/',views.seller_profile,name='sellerprofile'),
]
 

myapp/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Product(models.Model):
    def __str__(self):
        return self.name
        
    def get_absolute_url(slef):
        return reverse('myapp:products')

    seller_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)
    image = models.ImageField(blank=True,upload_to='images')

class OrderDetail(models.Model):
    customer_username = models.CharField(max_length=200)
    product = models.ForeignKey(to='Product',on_delete=models.PROTECT)
    amount = models.IntegerField()
    stripe_payment_intent = models.CharField(max_length=200)
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

myapp/views.py
from audioop import reverse
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Product,OrderDetail
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView,TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse,reverse_lazy
from django.core.paginator import Paginator

# stripe 
from django.http.response import HttpResponseNotFound,JsonResponse
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json
import stripe

# Create your views here.
def index(request):
    return HttpResponse("Hello There")

def products(request):
    page_obj = products = Product.objects.all()
    product_name = request.GET.get('product_name')
    if product_name!='' and product_name is not None:
        page_obj = products.filter(name__icontains=product_name)
    paginator = Paginator(page_obj,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj':page_obj
    }
    return render(request,'myapp/index.html',context)

#Class based view for above products [List view]
class ProductListView(ListView):
    model = Product
    template_name = 'myapp/index.html'
    context_object_name = 'products'
    paginate_by = 3

def productdetail(request,id):
    product = Product.objects.get(id=id)
    context = {
        'product':product
    }
    return render(request,'myapp/detail.html',context)

## Class based view for above productdetail view [DetailView]
class ProductDetailView(DetailView):
    model = Product
    template_name = 'myapp/detail.html'
    context_object_name = 'product'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView,self).get_context_data(**kwargs)
        context['stripe_publishable_key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context

@login_required
def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES['upload']
        seller_name = request.user
        product = Product(name=name, price=price, desc=desc, image=image,seller_name=seller_name)
        product.save()
    return render(request, 'myapp/addproduct.html')

#### class based view for creating a product

class ProductCreateView(CreateView):
    model = Product
    fields = ['name','price','desc','image','seller_name']
    #product_from.html


def update_product(request,id):
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/products')
    context = {
        'product':product
    }
    return render(request,'myapp/updateproduct.html',context)

## class based view for Updating a product
class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name','price','desc','image','seller_name']
    template_name_suffix = '_update_form'

def delete_product(request,id):
    product = Product.objects.get(id=id)
    context = {
        'product':product
    }
    if request.method == 'POST':
        product.delete()
        return redirect('/myapp/products')
    return render(request,'myapp/delete.html',context)

## class based view for Delete a product
class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('myapp:products')
    

def my_listings(request):
    products = Product.objects.filter(seller_name=request.user)
    context = {
        'products':products
    }
    return render(request,'myapp/mylistings.html',context)

@csrf_exempt
def create_checkout_session(request,id):
    product = get_object_or_404(Product,pk=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        customer_email = request.user.email,
        
        payment_method_types=['card'],
        line_items=[
            {
                'price_data':{
                    'currency':'usd',
                    'product_data':{
                        'name':product.name,
                    },
                    'unit_amount':int(product.price *100),
                },
                'quantity':1,
            }
        ],
        mode='payment',
        success_url = request.build_absolute_uri(reverse('myapp:success'))+"?session_id={CHECKOUT_SESSION_ID}",
        cancel_url= request.build_absolute_uri(
            reverse('myapp:failed')),
    )

    order = OrderDetail()
    order.customer_username = request.user.username
    order.product = product
    order.stripe_payment_intent = checkout_session['payment_intent']
    order.amount = int(product.price*100)
    order.save()
    return JsonResponse({'sessionId':checkout_session.id})

class PaymentSuccessView(TemplateView):
    template_name = 'myapp/payment_success.html'

    def get(self,request,*args,**kwargs):
        session_id = request.GET.get('session_id')
        if session_id is None:
            return HttpResponseNotFound()
        session = stripe.checkout.Session.retrieve(session_id)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        order = get_object_or_404(OrderDetail,stripe_payment_intent=session.payment_inten)
        order.has_paid = True
        order.save()
        return render(request,self.template_name)

class PaymentFailedView(TemplateView):
    template_name = 'myapp/payment_failed.html'

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">➕ Add Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name </label>
        <input class="shadow appearance-non border rounder py-2 px-3 mr-10 text-gray-700 " placeholder="Iphone" type="text" name="name" id="name">
    </div class="mb-4">
    <div>
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price </label>
        <input class="shadow appearance-non border rounder py-2 px-3 mr-10 text-gray-700 " placeholder="60000" type="text" name="price" id="price">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description </label>
        <input class="shadow appearance-non border rounder py-2 px-3 mr-10 text-gray-700 " placeholder="This is Iphone" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name </label>
        <input class=" py-2  " type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add product" value="Add product" id="">
    </div>
    
    
    
</form>
{% endblock %}

myapp/templates/myapp/base.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Buy&Sell</title>
    </head>
    <body>
        <nav class="bg-white shadow-lg">
            <div class="max-w-6xl mx-auto px-4">
                <div class="flex space-x-7">
                    <div class="flex">
                        <div>
                            <a href="{% url 'myapp:products' %}" class="flex items-center px-2 py-4">
                                <img class="h-8 w-8" src="{% static 'myapp/images/shopping.png' %}" alt="">
                            <span class="text-gray-500 font-semibold text-lg">Buy&Sell</span>
                            </a>  
                        </div>
                        <div class="items-center flex space-x-1">
                            <a href="{% url 'myapp:products' %}" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                            <a href="{% url 'myapp:add_product' %}" class="py-4 px-2 text-gray-500 font-semibold">Add Products</a>
                            
                            {% if user.is_authenticated %}
                            <a class="py-4 text-gray-500 font-semibold" href="{% url 'myapp:mylistings' %}">My Products</a>
                            <a class="py-4 px-10 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                            
                            <a class="py-4 px-40 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                            

                            {% else %}
                            <a class="py-4 px-40 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        {% block content %}

        {% endblock %}
    </body>
</html>

myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">Delete product</h1>
<form method="post" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
{% csrf_token %}
<div class="mb-4">
    <label class="block text-gray-700 text-sm font-bold mb-2">Are you sure you want to delete :</label>

</div>
<div class="mb-4">
    <label class="block text-gray-700 text-sm font-bold mb-2">
        {{product.name}}
    </label>
</div>
<div class="mb-4">
    <img src="{{product.image.url}}" a;t="">
</div>
<input class="bg-red-500 text-white px-5 py-2" type="submit" name="Confirm" value="Confirm">
<a class="button bg-green-500 text-white px-5 py-3 " href="{% url 'myapp:products' %}">Cancel</a>
</form>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{product.image.url}}" alt="">
    <div class="w-2/3 text-xl ml-10 mt-10">
        <div class="mt-5">{{product.name}}</div>
        <div class="mt-5 text-green-500">₹ {{product.price}}</div>
        <div class="mt-5 text-gray-700">{{product.desc}}</div>
        <div class="mt-5 text-gray-700">
            Posted by:
            <a class="mt-5 text-purple-500" href="{% url 'users:sellerprofile' product.seller_name.id %}">{{product.seller_name}}</a>
             </div>
        <div class="mt-5 text-gray-700">Contact: {{product.seller_name.profile.contact_number}}</div>
        <div>
            <button class="bg-green-500 text-white px-3 py-2 mt-2" id="checkout">Checkout</button>
        </div>
    </div>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">

        var stripe = Stripe('{{ stripe_publishable_key }}')
        var checkoutButton = document.getElementById('checkout')
        checkoutButton.addEventListener('click',function(){
            fetch("{% url 'myapp:api_checkout_session' id=product.id %}",{method:'POST',})
            .then(function(response){
                return response.json()
            })
            .then(function(session){
                return stripe.redirectToCheckout({sessionId:session.sessionId})
            })
            .then(function(result){
                if(result.error){
                    alert(result.error.message)
                }
            })
            .catch(function(error){
                console.error('Error',error)
            })
        })
    </script>
</div>

{% endblock %} 

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
    <!----site hero starts here-->
    <main class="mt-10 mx-auto  max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-10 lg:px-8 xl:mt-15">
        <div class="sm:text-center lg:text-left">
            <h1 class="text-3xl font-extrabold text-gray-900 sm:text-4xl md:text-5xl">
                <span class="block text-green-500 xl:inline">Premium Products</span> - 
                <span class="block  xl:inline">Non Premium Products</span>
            </h1>
            <p class="mt-3 text-base  test-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality used products across globe. Free Shipping </p>
        </div>
    </main>
    <!----site hero end here-->
    <div class="flex mt-5 p-10 justify-center">
        <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent Products</h2>
    </div>

    <div class="mt-3 p-7 justify-center">
        <h2>Search Products here :</h2>
        <form method="GET">
            <input class="font-bold text-lg text-gray-700" name="product_name" id="product_name" placeholder="Type a product to search" type="text">
        </form>
    </div>

    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5">
        <!--Card 1-->
    {% for product in page_obj %}
    <a href="{% url 'myapp:productdetail' product.id %}">
        <div class="rounded overflow-hidden shadow-lg">
            <img class="w-full" src="{{product.image.url}}" alt="">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">{{product.name}}</div>
                <div class="font-bold text-xl text-green-500 mb-2">₹ {{product.price}}</div>
                <div class="font-bold mb-2">Posted by: <span class="text-indigo-500">{{product.seller_name}}</span></div>
                <p class="text-grey-700">{{product.desc}}</p>
            </div>
        </div>
         
        
    </a>
    {% endfor %}
    </div>
    <!--pagination start-->
    <div class="pagination flex justify-center items-center mb-20">
        <span>
            {% if page_obj.has_previous %}
            <a class="text-sm font-medium borde py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page=1">First</a>
            <a class="text-sm font-medium borde py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page={{page_obj.previous_page_number}}">Previous</a>
            {% endif %}
            <span class="text-sm font-medium borde py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10">page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>
            {% if page_obj.has_next %}
            <a class="text-sm font-medium borde py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page={{page_obj.next_page_number}}">Next</a>
            <a class="text-sm font-medium borde py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page={{page_obj.paginator.num_pages}}">last</a>
            {% endif %}

        </span>
    </div>
    <!--pagination end-->
    
{% endblock %}

myapp/templates/myapp/mylistings.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="text-2xl m-10 p-10 font-bold"> My Products</div>
{% for product in products %}
    <div class="itemcontainer flex shadow-lg m-10 p-10">
        <span class="w-1/5">
            <img class="w-40 h-40" src="{{product.image.url}}">
        </span>
        <span class="w-2/5">
            <div class="font-bold text-gray-700">{{product.name}}</div>
            <div class="text-green-500">₹ {{product.price}}</div>
            <div>{{product.desc}}</div>
        </span>
        <span class="w-1/5">
                <a class="bg-green-500 text-white font-bold px-5 py-2" href="{% url 'myapp:update_product' product.id %}">Edit</a>
        </span>
        <span class="w-1/5">
            <a class="bg-Red-500 text-white font-bold px-5 py-2" href="{% url 'myapp:delete_product' product.id %}">Delete</a>
    </span>
    </div>
{% endfor %}
{% endblock %}

myapp/templates/myapp/payment_failed.html
{% extends 'myapp/base.html' %}
{% block content %}
    <p> payment failed </p>
{% endblock %}

myapp/templates/myapp/payment_success.html
{% extends 'myapp/base.html' %}
{% block content %}
    <p>We received your order payment</p>
{% endblock %}

myapp/templates/myapp/product_confirm_delete.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold"> Delete Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    {{ form }}

    <input class="bg-green-500 text-white px-5 py-2" type="submit" value="Confirm" name="",id="">
    
</form>


{% endblock %}

myapp/templates/myapp/product_form.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">➕ Add Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name </label>
         
         <div class="shadow appearance-non border rounder w-1/4 py-2 px-3 mr-10 text-gray-700 " >
            {{form.name}}
         </div>
        
    </div class="mb-4">
    <div>
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price </label>
        <div class="shadow appearance-non border rounder w-1/4 py-2 px-3 mr-10 text-gray-700 " >
            {{form.price}}
         </div>
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description </label>
        <div class="shadow appearance-non border rounder w-1/4 py-2 px-3 mr-10 text-gray-700 " >
            {{form.desc}}
         </div>
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Image </label>
        <div class="shadow appearance-non border rounder w-1/4 py-2 px-3 mr-10 text-gray-700 " >
            {{form.image}}
         </div>
    </div>

    <div class="mb-4">
        <div class=" hidden shadow appearance-non border rounder w-1/4 py-2 px-3 mr-10 text-gray-700 " >
            {{form.seller_name}}
         </div>
    </div>
    
    <div class="mb-4">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add product" value="Add product" id="">
    </div>
    
    
    
</form>

{% endblock %}

myapp/templates/myapp/product_update_form.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">➕ Update Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
    <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Update",id="">
    
</form>


{% endblock %}

myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl m-10 font-bold">➕ Update Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name </label>
        <input class="shadow appearance-non border rounder py-2 px-3 mr-10 text-gray-700 " placeholder="Iphone" value="{{product.name}}" type="text" name="name" id="name">
    </div class="mb-4">
    <div>
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price </label>
        <input class="shadow appearance-non border rounder py-2 px-3 mr-10 text-gray-700 " placeholder="60000" value="{{product.price}}" type="text" name="price" id="price">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description </label>
        <input class="shadow appearance-non border rounder py-2 px-3 mr-10 text-gray-700 " placeholder="This is Iphone" value="{{product.desc}}" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <img class="w-20 h-20" src="{{product.image.url}}" alt="">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Image </label>
        <input class=" py-2  " type="file" accept="image/*" name="upload" id="upload">
    </div>
    <div class="mb-4">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add product" value="Update product" id="">
    </div>
    
    
    
</form>
{% endblock %}